LINKED_LIBS= libElf    \
             libLINK   \
             libUtils  \
             libArchive \
			 libIOInterface  \
			 libTest

BUILD_TIME_TESTS=mismatch
CPP_TAGS_FILE=testStlMismatch-c++.test

include ../../makefile.include
