LINKED_LIBS= libElf    \
             libLINK   \
             libUtils  \
             libArchive \
			 libIOInterface \
			 libTest

BUILD_TIME_TESTS=objectHeaderTable elfStringTable sectionHeader unitialisedMemory symbols programHeader sectionData elf2elf 
CPP_TAGS_FILE=testelf2elf-c++.tags

USE_BOOST=YES

MODE=CPP

include ../../makefile.include
