LINKED_LIBS= libElf    \
             libLINK   \
             libUtils  \
             libArchive \
			 libIOInterface \
			 libTest

BUILD_TIME_TESTS=objectHeaderTable
CPP_TAGS_FILE=testelf2elf-c++.tags

include ../../makefile.include
