LINKED_LIBS= libElf\
             libUtils  \
             libIOInterface \
             libTest

BUILD_TIME_TESTS=stringTable
CPP_TAGS_FILE=testStringTable-c++.test
MODE=CPP

include ../../makefile.include
