SOURCES=$(shell echo *.cpp)

LINKED_LIBS= libElf    \
             libLINK   \
             libUtils  \
             libArchive \
             libIOInterface 

EXECUTABLE=addExec
CPP_TAGS_FILE=addExec-c++.tags

include ../../makefile.include
