SOURCES=$(shell echo *.cpp)

LINKED_LIBS= libElf    \
             libLINK   \
             libUtils  \
             libArchive \
			 libIOInterface 

EXECUTABLE=elf2Link
CPP_TAGS_FILE=elf2Link-c++.tags

include ../../makefile.include
