SOURCES=$(shell echo *.cpp)

LINKED_LIBS= libElf    \
             libLINK   \
             libUtils  \
             libArchive \
			 libIOInterface 
EXECUTABLE=elf2elf
CPP_TAGS_FILE=elf2elf-c++.tags

include ../../makefile.include
