LINKED_LIBS= libElf\
             libUtils  \
             libIOInterface \
             libTest

BUILD_TIME_TESTS=stdWriter stdReader
CPP_TAGS_FILE=testStdWriter.c++tags

include ../../makefile.include
