EXPORT_INCLUDES=$(shell echo *.h)
SOURCES=$(shell echo *.cpp)

TARGET_LIB=libRuntime
LINKED_LIBS=libUtils libIOInterface libElf
MODE=CPP

CPP_TAGS_FILE=libRuntime-c++.tags

include ../../makefile.include
