SOURCES=$(shell echo *.cpp)

LINKED_LIBS= libElf    \
             libLINK   \
             libUtils  \
             libArchive \
			 libIOInterface 

EXECUTABLE=elf2Link

include ../makefile.include
