LINKED_LIBS= libUtils  \
			 libIOInterface \
			 libTest

BUILD_TIME_TESTS=dataVectorTest binaryReaderTests binaryWriterTests funcOverload
CPP_TAGS_FILE=testIOInterface-c++.tags
FATAL_WARNINGS=YES

include ../../makefile.include
